const countries = [
    "Iceland",
    "Turkey",
    "Bosnia and Herzegovina",
    "Sweden",
    "Armenia",
    "Malta",
    "Israel",
    "Portugal",
    "Romania",
    "Macedonia",
    "Montenegro",
    "Finland",
    "Belarus",
    "Switzerland",
    "Andorra",
    "Bulgaria",
    "Belgium",
    "Czech Republic",
]

export const countryNameMap = {
    "iceland":"Iceland",
    "turkey": "Turkey",
    "bosnia and herzegovina":"Bosnia and Herzegovina",
    "sweden" :"Sweden",
    "armenia" :"Armenia",
    "malta" :"Malta",
    "israel":"Israel",
    "portugal":"Portugal",
    "romania": "Romania",
    "macedonia": "Macedonia",
    "montenegro":"Montenegro",
    "finland": "Finland",
    "belarus": "Belarus",
    "switzerland":"Switzerland",
    "andorra": "Andorra",
    "bulgaria":"Bulgaria",
    "belgium": "Belgium",
    "czech republic":"Czech Republic",
    "serbia": "Serbia"
}

export const countryFlagMap = {
    "turkey": "TR.png",
    "bosnia and herzegovina": "BA.png",
    "sweden" :"SE.png",
    "armenia" : "AM.png",
    "malta" : "MT.png",
    "israel": "IL.png",
    "portugal": "PT.png",
    "romania": "RO.png",
    "iceland": "IS.png",
    "macedonia": "MK.png",
    "montenegro": "ME.png",
    "finland": "FI.png",
    "belarus": "BY.png",
    "switzerland": "CH.png",
    "andorra": "AD.png",
    "bulgaria": "BG.png",
    "belgium": "BE.png",
    "czech republic": "CZ.png",
    "serbia": "RS.png"
}

export default countries