export const countries = [
    "armenia",
    "estonia",
    "malta",
    "iceland",
    "bosnia and herzegovina",
    "ukraine",
    "macedonia",
    "monaco",
    "finland",
    "turkey",
    "sweden",
    "portugal",
    "russia",
    "belarus",
    "lithuania",
    "cyprus",
    "poland",
    "bulgaria",
    "belgium",
    "andorra",
    "denmark",
    "netherlands",
    "ireland"
    // "azerbaijan",
    // "moldova",
    // "albania",
    // "ukraine",
    // "estonia",
    // "croatia",
    // "macedonia",
    // "malta",
    // "russia",
    // "bosnia and herzegovina",
    // "andorra",
    // "armenia",
]

export const countryNameMap = {
    "croatia": "Croatia",
    "ireland": "Ireland",
    "norway": "Norway",
    "denmark": "Blandmark",
    "azerbaijan": "Azjbn",
    "greece": "PAME ELLADA",
    "moldova": "Moldova",
    "albania": "Albania",
    "ukraine": "Ukraine, The",
    "estonia": "Estonia",
    "macedonia": "Macedonia",
    "france": "France",
    "united kingdom": "United Kingdom, The",
    "spain": "ESPAIN WILL WIN",
    "germany": "Germany",
    "finland": "Finland",
    "malta": "Matla",
    "portugal":"Portugal",
    "russia": "Russia",
    "turkey": "Turkey",
    "iceland":"Iceland",
    "bosnia and herzegovina":"Bosnia Herchnegova",
    "andorra": "Andorra",
    "armenia" :"Armenia",
    "switzerland": "Switzerland",
    "yugoslavia": "Former Yugoslav Republic, the",
    "belgium": "Belgium",
    "netherlands": "Netherlands, The",
    "israel": "Israel",
    "luxembourg": "Luxembourg",
    "sweden": "Sweden",
    "cyprus": "Cyprus",
    "italy": "Italy",
    "austria": "Austria",
    "monaco": "Monaco",
    "poland": "Poland",
    "lithuania": "Not the Winners",
    "bulgaria": "Bulgaria",
    "belarus": "Belarus"
}

export const countryFlagMap = {
    "turkey": "TR.png",
    "bosnia and herzegovina": "BA.png",
    "sweden" :"SE.png",
    "armenia" : "AM.png",
    "malta" : "MT.png",
    "israel": "IL.png",
    "portugal": "PT.png",
    "romania": "RO.png",
    "iceland": "IS.png",
    "macedonia": "MK.png",
    "montenegro": "ME.png",
    "finland": "FI.png",
    "belarus": "BY.png",
    "switzerland": "CH.png",
    "andorra": "AD.png",
    "bulgaria": "BG.png",
    "belgium": "BE.png",
    "czech republic": "CZ.png",
    "serbia": "RS.png",
    "moldova": "MD.png",
    "croatia": "HR.png",
    "ireland": "IE.png",
    "latvia": "LV.png",
    "poland": "PL.png",
    "norway": "NO.png",
    "cyprus": "CY.png",
    "slovakia": "SK.png",
    "denmark": "DK.png",
    "slovenia": "SI.png",
    "hungary": "HU.png",
    "azerbaijan": "AZ.png",
    "greece": "GR.png",
    "lithuania": "LT.png",
    "albania": "AL.png",
    "ukraine": "UA.png",
    "estonia": "EE.png",
    "netherlands": "NL.png",
    "united kingdom": "GB.png",
    "france": "FR.png",
    "germany": "DE.png",
    "russia": "RU.png",
    "spain": "ES.png",
    "yugoslavia": "YU.png",
    "luxembourg": "LU.png",
    "italy": "IT.png",
    "austria": "AT.png",
    "monaco": "MC.png"
}


export const rankToPointsMap = {
    "1": 12,
    "2": 10,
    "3": 8,
    "4": 7,
    "5": 6,
    "6": 5,
    "7": 4,
    "8": 3,
    "9": 2,
    "10": 1,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0
}


export default countries
