export const countries = [
    "Croatia",
    "Ireland",
    "Latvia",
    "Serbia",
    "Poland",
    "Norway",
    "Cyprus",
    "Slovakia",
    "Denmark",
    "Slovenia",
    "Hungary",
    "Azerbaijan",
    "Greece",
    "Lithuania",
    "Moldova",
    "Albania",
    "Ukraine",
    "Estonia",
    "Netherlands",
]

export const countryNameMap = {

    "croatia": "Croatia",
    "ireland": "Ireland",
    "norway": "Norway",
    "denmark": "Bland Land",
    "azerbaijan": "Azerbaijan",
    "greece": "Greece",
    "moldova": "Moldova",
    "albania": "Albania",
    "ukraine": "Ukraine",
    "estonia": "Estonia"
}

export const countryFlagMap = {
    "turkey": "TR.png",
    "bosnia and herzegovina": "BA.png",
    "sweden" :"SE.png",
    "armenia" : "AM.png",
    "malta" : "MT.png",
    "israel": "IL.png",
    "portugal": "PT.png",
    "romania": "RO.png",
    "iceland": "IS.png",
    "macedonia": "MK.png",
    "montenegro": "ME.png",
    "finland": "FI.png",
    "belarus": "BY.png",
    "switzerland": "CH.png",
    "andorra": "AD.png",
    "bulgaria": "BG.png",
    "belgium": "BE.png",
    "czech republic": "CZ.png",
    "serbia": "RS.png",
    "moldova": "MD.png",
    "croatia": "HR.png",
    "ireland": "IE.png",
    "latvia": "LV.png",
    "poland": "PL.png",
    "norway": "NO.png",
    "cyprus": "CY.png",
    "slovakia": "SK.png",
    "denmark": "DK.png",
    "slovenia": "SI.png",
    "hungary": "HU.png",
    "azerbaijan": "AZ.png",
    "greece": "GR.png",
    "lithuania": "LT.png",
    "albania": "AL.png",
    "ukraine": "UA.png",
    "estonia": "EE.png",
    "netherlands": "NL.png",
}


export const rankToPointsMap = {
    "1": 12,
    "2": 10,
    "3": 8,
    "4": 7,
    "5": 6,
    "6": 5,
    "7": 4,
    "8": 3,
    "9": 2,
    "10": 1,
    "11": 0,
    "12": 0,
    "13": 0,
    "14": 0,
    "15": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "19": 0,
    "20": 0,
    "21": 0,
    "22": 0,
    "23": 0,
    "24": 0,
    "25": 0,
    "26": 0,
    "27": 0,
    "28": 0,
    "29": 0
}


export default countries